name = "FluidInducedAseismicSlip"
uuid = "681bf5af-8c4c-4c72-97a1-a72de5d27596"
authors = ["Antoine Jacquey <antoine.jacquey@tufts.edu> and contributors"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FastGaussQuadrature = "0.4"
Plots = "1"
Revise = "3"
SpecialFunctions = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
